const $ = id => document.getElementById(id);
const panel = $('rateAlertsPanel'); const openButton = $('openRateAlertsBtn'); const closeButton = $('closeRateAlertsBtn');
let previousFocus = null; let alerts = [];
const credential = () => ({ id: localStorage.getItem('rateAlertDeviceId'), secret: localStorage.getItem('rateAlertDeviceSecret') });
function ensureCredential() { if (!credential().id) { const bytes = crypto.getRandomValues(new Uint8Array(32)); localStorage.setItem('rateAlertDeviceId', crypto.randomUUID()); localStorage.setItem('rateAlertDeviceSecret', btoa(String.fromCharCode(...bytes)).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')); } return credential(); }
const headers = (json = false) => { const c = credential(); return { ...(json ? { 'Content-Type': 'application/json' } : {}), ...(c.id ? { 'X-Device-Id': c.id, 'X-Device-Secret': c.secret } : {}) }; };
async function request(url, options = {}) { const response = await fetch(url, { ...options, headers: { ...headers(Boolean(options.body)), ...options.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'No se pudo completar la solicitud'); return { data, response }; }
function supported() { return 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window; }
function permissionState() { if (!supported()) return 'unsupported'; return Notification.permission === 'default' ? 'prompt' : Notification.permission; }
function updatePermission() { const state = permissionState(); const messages = { unsupported: 'Este navegador no admite Web Push.', prompt: 'Activa las notificaciones para recibir alertas.', granted: 'Notificaciones activas.', denied: 'Las notificaciones están bloqueadas. Puedes habilitarlas en los ajustes del navegador.' }; $('rateAlertPermission').textContent = messages[state]; $('enableRateAlertsBtn').hidden = state !== 'prompt'; $('testRateAlertBtn').hidden = state !== 'granted'; if (/iPhone|iPad|iPod/.test(navigator.userAgent) && !navigator.standalone) $('rateAlertPermission').textContent = 'Para recibir alertas en iPhone, instala CalcuFlow desde Safari usando Compartir → Añadir a pantalla de inicio.'; }
function base64(value) { const pad = '='.repeat((4 - value.length % 4) % 4); const raw = atob((value + pad).replace(/-/g, '+').replace(/_/g, '/')); return Uint8Array.from([...raw].map(c => c.charCodeAt(0))); }
async function subscribe() { if (!supported()) throw new Error('Web Push no está disponible'); if (Notification.permission === 'denied') throw new Error('Permiso de notificaciones bloqueado'); if (Notification.permission === 'default') { if (!confirm('CalcuFlow usará notificaciones solo para avisarte cuando una tasa alcance el cambio que elijas.')) throw new Error('Activación cancelada'); if (await Notification.requestPermission() !== 'granted') throw new Error('Permiso no concedido'); } ensureCredential();
  const registration = await navigator.serviceWorker.ready; let subscription = await registration.pushManager.getSubscription(); if (!subscription) { const { data } = await request('/api/config'); subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: base64(data.vapidPublicKey) }); }
  const { response } = await request('/api/push/subscribe', { method: 'POST', body: JSON.stringify({ subscription: subscription.toJSON() }) }); const id = response.headers.get('X-Device-Id'); const secret = response.headers.get('X-Device-Secret'); if (id && secret) { localStorage.setItem('rateAlertDeviceId', id); localStorage.setItem('rateAlertDeviceSecret', secret); } updatePermission(); }
function currentRate() { return Number($( $('alertRateType').value === 'bcv' ? 'bcvRate' : 'p2pRate').value); }
function updateForm() { const percent = $('alertMeasurement').value === 'percent'; const values = percent ? [.5, 1, 2, 5] : [5, 10, 15]; $('alertThreshold').min = percent ? '.1' : '1'; $('alertThreshold').step = percent ? '.1' : '1'; $('alertThresholdUnit').textContent = percent ? '%' : 'Bs'; $('alertQuickValues').innerHTML = values.map(v => `<button type="button" data-value="${v}">${v}${percent ? '%' : ' Bs'}</button>`).join(''); $('alertQuickValues').querySelectorAll('button').forEach(button => button.onclick = () => { $('alertThreshold').value = button.dataset.value; explain(); }); explain(); }
function explain() { const rate = currentRate(); const value = Number($('alertThreshold').value); const direction = $('alertDirection').value; $('alertReference').textContent = Number.isFinite(rate) && rate > 0 ? `Referencia actual: ${rate.toLocaleString('es-VE', { maximumFractionDigits: 2 })} Bs` : 'Actualiza las tasas para crear una alerta.'; if (!(rate > 0) || !(value > 0)) return $('alertExplanation').textContent = 'Elige el cambio mínimo que quieres vigilar.'; const delta = $('alertMeasurement').value === 'percent' ? rate * value / 100 : value; const trigger = direction === 'up' ? rate + delta : rate - delta; const words = { up: 'suba', down: 'baje', any: 'cambie en cualquier dirección' }; $('alertExplanation').textContent = direction === 'any' ? `Te avisaremos cuando la tasa ${words[direction]} al menos ${value}${$('alertMeasurement').value === 'percent' ? '%' : ' Bs'}.` : `Te avisaremos cuando ${words[direction]} hasta ${trigger.toLocaleString('es-VE', { maximumFractionDigits: 2 })} Bs.`; }
function render() { $('rateAlertsList').innerHTML = alerts.length ? alerts.map(a => `<article class="alert-item"><div><strong>${a.rate_type === 'bcv' ? 'BCV' : 'USDT P2P'} · ${{ up: 'Sube', down: 'Baja', any: 'Cualquier cambio' }[a.direction]}</strong><span>${a.threshold} ${a.measurement === 'percent' ? '%' : 'Bs'} · Base ${Number(a.baseline_rate).toLocaleString('es-VE')} Bs</span><span>${a.recurring ? 'Recurrente' : 'Una vez'} · ${a.active ? 'Activa' : 'Inactiva'}</span></div><div><button type="button" data-toggle="${a.id}" data-active="${!a.active}">${a.active ? 'Desactivar' : 'Activar'}</button><button type="button" data-delete="${a.id}">Eliminar</button></div></article>`).join('') : '<p class="alert-empty">Todavía no tienes alertas.</p>'; }
async function load() { if (!credential().id) return; try { alerts = (await request('/api/alerts')).data; render(); } catch (e) { $('rateAlertPermission').textContent = e.message; } }
function open() { previousFocus = document.activeElement; panel.classList.add('open'); panel.setAttribute('aria-hidden', 'false'); openButton.setAttribute('aria-expanded', 'true'); document.body.classList.add('modal-open'); closeButton.focus(); updatePermission(); updateForm(); load(); }
function close() { panel.classList.remove('open'); panel.setAttribute('aria-hidden', 'true'); openButton.setAttribute('aria-expanded', 'false'); document.body.classList.remove('modal-open'); previousFocus?.focus(); }
openButton?.addEventListener('click', open); closeButton?.addEventListener('click', close); panel?.addEventListener('click', e => { if (e.target === panel) close(); });
document.addEventListener('keydown', e => { if (!panel.classList.contains('open')) return; if (e.key === 'Escape') close(); if (e.key === 'Tab') { const nodes = [...panel.querySelectorAll('button:not([hidden]),input,select')].filter(n => !n.disabled); const first = nodes[0], last = nodes.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } });
$('enableRateAlertsBtn')?.addEventListener('click', () => subscribe().catch(e => $('rateAlertPermission').textContent = e.message)); $('alertMeasurement')?.addEventListener('change', updateForm); $('alertRateType')?.addEventListener('change', explain); $('alertDirection')?.addEventListener('change', explain); $('alertThreshold')?.addEventListener('input', explain);
$('rateAlertForm')?.addEventListener('submit', async e => { e.preventDefault(); try { await subscribe(); const baseline = currentRate(); if (!(baseline > 0)) throw new Error('Actualiza las tasas antes de crear la alerta'); await request('/api/alerts', { method: 'POST', body: JSON.stringify({ rate_type: $('alertRateType').value, direction: $('alertDirection').value, measurement: $('alertMeasurement').value, threshold: Number($('alertThreshold').value), baseline_rate: baseline, recurring: $('alertRecurring').checked }) }); e.target.reset(); updateForm(); await load(); } catch (error) { $('rateAlertPermission').textContent = error.message; } });
$('testRateAlertBtn')?.addEventListener('click', async () => { try { await request('/api/push/test', { method: 'POST', body: '{}' }); $('rateAlertPermission').textContent = 'Notificación de prueba enviada.'; } catch (e) { $('rateAlertPermission').textContent = e.message; } });
$('rateAlertsList')?.addEventListener('click', async e => { const id = e.target.dataset.toggle || e.target.dataset.delete; if (!id) return; try { await request(`/api/alerts/${id}`, e.target.dataset.delete ? { method: 'DELETE' } : { method: 'PATCH', body: JSON.stringify({ active: e.target.dataset.active === 'true' }) }); await load(); } catch (error) { $('rateAlertPermission').textContent = error.message; } });
if (new URLSearchParams(location.search).get('alerts') === 'open') open();
